sudo: required

services:
  - docker

script:
    - docker build -t riemann .

    - if [ -z ${TRAVIS_TAG} ]; then echo "No push"; else docker login -u="$DOCKER_USER" -p="$DOCKER_PASS" && docker tag riemann cortwave/riemann:latest &&  docker push cortwave/riemann:latest && docker tag riemann cortwave/riemann:$TRAVIS_TAG && docker push cortwave/riemann:$TRAVIS_TAG; fi
